config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get "user/:id/follow_users" => "users#follow_users", as: "follow_users"
  get "user/:id/follower_users" => "users#follower_users", as: "follower_users"

  get "search" => "searches#search"

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    # redirect_to book_path(book)
    @showbook = Book.find(params[:book_id])
    @book_comment = BookComment.new
    @user = User.find(@showbook.user_id)
    @book = Book.new
    if book_comments = BookComment.find_by(book_id: params[:book_id])
      @comment_user = User.find(book_comments.user_id)
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to book_path(params[:book_id])
    @showbook = Book.find(params[:book_id])
    @book_comment = BookComment.new
    @user = User.find(@showbook.user_id)
    @book = Book.new
    if book_comments = BookComment.find_by(book_id: params[:book_id])
      @comment_user = User.find(book_comments.user_id)
    end
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_destroy.html.erb
<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[showbook, book_comment]) do |f| %>
  <%= f.text_area :comment, rows:'5', class: "form-control" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<% showbook.book_comments.each do |book_comment| %>
<tr>
  <td>
    <%= attachment_image_tag book_comment.user, :profile_image, :fill, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %><br>
    <%= link_to book_comment.user.name, user_path(comment_user) %>
  </td>
  <td>
    <p><%= book_comment.comment %></p>
  </td>
  <td>
    <% if book_comment.user == current_user %>
      <div class="comment-delete">
        <!--destroyボタンの部分テンプレート-->
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </td>
  <% end %>
  </td>
</tr>

app/views/book_comments/create.js.erb
$(".form-control").val("");
$(".book_comments_index").html("<%= j(render "book_comments/index", {showbook: @showbook, comment_user: @comment_user}) %>");
$(".new_comment").html("<%= j(render "book_comments/form", {showbook: @showbook, book_comment: @book_comment}) %>");

app/views/book_comments/destroy.js.erb
$(".book_comments_index").html("<%= j(render "book_comments/index", {showbook: @showbook, comment_user: @comment_user}) %>");
$(".new_comment").html("<%= j(render "book_comments/form", {showbook: @showbook, book_comment: @book_comment}) %>");