config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get "user/:id/follow_users" => "users#follow_users", as: "follow_users"
  get "user/:id/follower_users" => "users#follower_users", as: "follower_users"

  get "search" => "searches#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # UseモデルはRelationshipクラスにfollowerを"follower_id"keyで持ってます
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # そして、followerを通して、followed_usersを持っています。ちなみにその際のkeyとなるカラムはfollowedです。（throughとsourceは"_id"が隠れている）
  has_many :following, through: :follower, source: :followed
  #上記２コードの裏返し
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed, source: :follower

  def following?(other_user)
    follower.find_by_followed_id(other_user.id)
  end

  def self.search(search, word)
    if search == "forward_match"
      @users = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @users = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @users = User.where("name", "#{word}")
    elsif search == "partial_match"
      @users = User.where("name LIKE?", "%#{word}%")
    else
      @users = User.all
    end
  end




  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      @users = User.all
      render "users/edit"
    end
  end

  def follow_users
    user = User.find(params[:id])
    @users = user.following
    # binding.pry
  end

  def follower_users
    user = User.find(params[:id])
    @users = user.followers
    # binding.pry
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  # beforeフィルター

  #ログイン済みユーザーかどうか確認
  def logged_in_user
    user = User.find(params[:id])
    unless current_user.id == user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:@book, url:"/books", local:true do |f| %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success"%>
  </div>
<% end %>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:"jpeg", fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <%= link_to user.following.count, follow_users_path(user) %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <%= link_to user.followers.count, follower_users_path(user) %>
      </th>
    </tr>
  </tbody>
</table>
<div class="row">
  <% if user.id != current_user.id %>
    <% if current_user.following?(user) %>
      <%= link_to user_relationships_path(user), class: "btn btn-info", method: :delete do %>
        フォロー外す
      <% end %>
    <% else %>
      <%= link_to user_relationships_path(user), class: "btn btn-success", method: :post do %>
        フォローする
      <% end %>
    <% end %>
  <% end %>
</div>
<div><br></div>
<div class="row">
  <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </div>
        <% end %>

        <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id: "inputName", placeholder:"名前", class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_field :introduction, autofocus: true, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/follow_users.html.erb
<main>
  <div></div>
</main>

app/views/users/follower_users.html.erb
<div class="col-md-8 offset-md-1">
  <h2>Follow Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, size:"40x40", format:"jpeg", fallback: "no_image.jpg" %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          フォロー数：<%= user.following.count %>
        </td>
        <td>
          フォロワー数：<%= user.followers.count %>
        </td>
        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%# Userinfo部分テンプレート %>
        <%= render "users/userinfo", user: current_user %>

        <%# Newbook部分テンプレート %>
        <%= render "books/form", book: @book %>

      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, size:"40x40", format:"jpeg", fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                フォロー数：<%= user.following.count %>
              </td>
              <td>
                フォロワー数：<%= user.followers.count %>
              </td>
              <!--フォローする/外すボタンの挿入-->
              <td>
                <% if user.id != current_user.id %>
                  <% if current_user.following?(user) %>
                    <%= link_to user_relationships_path(user), method: :delete do %>
                      フォロー外す
                    <% end %>
                  <% else %>
                    <%= link_to user_relationships_path(user), method: :post do %>
                      フォローする
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%# Userinfo部分テンプレート %>
        <%= render "users/userinfo", user: @user %>

        <%# Newbook部分テンプレート %>
        <%= render "books/form", book: @book %>

      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, size: "40x40", format:"jpeg", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>