config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get "user/:id/follow_users" => "users#follow_users", as: "follow_users"
  get "user/:id/follower_users" => "users#follower_users", as: "follower_users"

  get "search" => "searches#search"

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    @word = params[:word]

    if @range == "1"
      @users = User.search(search, word)
    else
      @books = Book.search(search, word)
    end

  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<!--本を検索-->
<% if @range == "2" %>
<h2>Books search for "<%= "#{@word}" %>"</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.id) do %>
          <%= attachment_image_tag book.user, :profile_image, size:"40x40", format:"jpeg", fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<!--ユーザーを検索-->
<h2>Users search for "<%= "#{@word}" %>"</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= attachment_image_tag user, :profile_image, :fill, size:"40x40", format:"jpeg", fallback: "no_image.jpg" %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= link_to "Show", user_path(user.id) %>
      </td>
    </tr>
    <% end %>
  </tbody>
<% end %>
</table>