config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get "user/:id/follow_users" => "users#follow_users", as: "follow_users"
  get "user/:id/follower_users" => "users#follower_users", as: "follower_users"

  get "search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
      @books = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @books = Book.where("title LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @books = Book.where("title", "#{word}")
    elsif search == "partial_match"
      @books = Book.where("title LIKE?", "%#{word}%")
    else
      @books = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # UseモデルはRelationshipクラスにfollowerを"follower_id"keyで持ってます
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # そして、followerを通して、followed_usersを持っています。ちなみにその際のkeyとなるカラムはfollowedです。（throughとsourceは"_id"が隠れている）
  has_many :following, through: :follower, source: :followed
  #上記２コードの裏返し
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :followed, source: :follower

  def following?(other_user)
    follower.find_by_followed_id(other_user.id)
  end

  def self.search(search, word)
    if search == "forward_match"
      @users = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @users = User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @users = User.where("name", "#{word}")
    elsif search == "partial_match"
      @users = User.where("name LIKE?", "%#{word}%")
    else
      @users = User.all
    end
  end




  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user, only: [:edit]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render "books/index"
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @showbook = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = User.find(@showbook.user_id)
    if book_comments = BookComment.find_by(book_id: params[:id])
      @comment_user = User.find(book_comments.user_id)
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render "books/edit"
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  # beforeフィルター

  #ログイン済みユーザーかどうか確認

  def logged_in_user
    book = Book.find(params[:id])
    unless current_user.id == book.user_id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    # redirect_to request.referer
    @showbook = Book.find(params[:book_id])
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    # redirect_to request.referer
    @showbook = Book.find(params[:book_id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    @word = params[:word]

    if @range == "1"
      @users = User.search(search, word)
    else
      @books = Book.search(search, word)
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      @users = User.all
      render "users/edit"
    end
  end

  def follow_users
    user = User.find(params[:id])
    @users = user.following
    # binding.pry
  end

  def follower_users
    user = User.find(params[:id])
    @users = user.followers
    # binding.pry
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  # beforeフィルター

  #ログイン済みユーザーかどうか確認
  def logged_in_user
    user = User.find(params[:id])
    unless current_user.id == user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=diveice-width", initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <% if user_signed_in? %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li>
                <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>
            </ul>
          </div>
          <% else %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle Navigation">
            <spna class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "About", about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            </ul>
          </div>
          <% end %>
        </div>
      </nav>
    <%#　検索窓 %>
    <div class="search">
      <% if user_signed_in? %>
        <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag (:word) %>
          <%= select_tag "range", options_for_select([["User", "1"], ["Book", "2"]]) %>
          <%= select_tag "search", options_for_select([["前方一致", "forward_match"], ["後方一致", "backward_match"], ["完全一致", "perfect_match"], ["部分一致", "partial_match"]]) %>
          <%= submit_tag "検索" %>
        <% end %>
      <% end %>
    </div>
    </header>

    <p id="notice"><%= flash[:notice] %></p>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>